before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
    ldflags:
      - -s -w -extldflags=-static -X mtui/app.Version={{.Version}}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
- image_templates:
    - "ghcr.io/minetest-go/mtui:{{ .Version }}"
    - "ghcr.io/minetest-go/mtui:latest"
  dockerfile: Dockerfile