
services:
 ui_webapp:
  image: node:22.22.3
  volumes:
   - "./:/app"
  working_dir: /app/public
  command: ["npm", "ci"]

 ui:
  image: golang:1.26.2
  networks:
   default: {}
   mtui_internal:
    aliases:
      - mtui
  environment:
   WORLD_DIR: "/world"
   WEBDEV: "true"
   API_KEY: "mykey"
   LOGLEVEL: debug
   SERVER_NAME: "dev-server"
   ENABLE_FEATURES: "api,shell,luashell,minetest_config,docker,modmanagement,signup,chat,minetest_web"
   INSTALL_MTUI_MOD: "true"
   MINETEST_CONFIG: "/world/minetest.conf"
   GEOIP_API: "https://hosting.minetest.ch/api/geoip"
   DOCKER_MINETEST_CONFIG: "/world/minetest.conf"
   DOCKER_MINETEST_PORT: 30000
   DOCKER_HOSTNAME: "ui"
#   DOCKER_NETWORK: "mtui_default"
   DOCKER_INTERNAL_NETWORK: "mtui_internal"
   DOCKER_WORLD_DIR: "/world"
   DOCKER_CONTAINER_PREFIX: "mtui"
   DOCKER_AUTOINSTALL_ENGINE: "true"
  ports:
    - 8080:8080
  volumes:
   - "./minetest.conf:/world/minetest.conf"
   - "./:/app"
   - "world_dir:/world"
   - "./cache/go_dir:/go"
   - "./cache/go_cache:/.cache"
   - "docker-socket:/var/run/"
  working_dir: /app
  command: ["go", "run", "."]

 dind:
  image: docker:29.5.0-dind
  restart: always
  privileged: true
  volumes:
  - "docker-socket:/var/run/"
  - "dind-data:/var/lib/docker"
  - "world_dir:/world"
  - "./runner:/runner"
  environment:
    DOCKER_TLS_CERTDIR: ""
  command:
  - --storage-driver=overlay2
  - --tls=false

volumes:
  world_dir: {}
  docker-socket: {}
  dind-data: {}

networks:
  mtui_internal:
    name: mtui_internal
