
services:
 ui_webapp:
  image: node:22.22.3
  volumes:
   - "./:/app"
  working_dir: /app/public
  command: ["npm", "ci"]

 ui:
  image: golang:1.27.1
  environment:
   WORLD_DIR: "/world"
   WEBDEV: "true"
   API_KEY: "mykey"
   LOGLEVEL: debug
   SERVER_NAME: "dev-server"
   ENABLE_FEATURES: "api,shell,luashell,minetest_config,docker,modmanagement,signup,chat,minetest_web"
   MINETEST_CONFIG: "/world/minetest.conf"
  ports:
    - 8080:8080
  volumes:
   - "./minetest.conf:/world/minetest.conf"
   - "./:/app"
   - "world_dir:/world"
   - "./cache/go_dir:/go"
   - "./cache/go_cache:/.cache"
   - "/var/run/docker.sock:/var/run/docker.sock:ro"
  working_dir: /app
  command: ["go", "run", "."]

volumes:
  world_dir: {}
